<?php

/**
 * Inline critical CSS and load the main stylesheet asynchronously.
 *
 * How it works:
 * - critical.min.css is generated by `gulp critical` and contains only
 *   above-the-fold styles extracted from style.min.css.
 * - That file is inlined directly into <head> so the browser can render
 *   immediately without waiting for a network request.
 * - style.min.css is then loaded asynchronously (non-render-blocking)
 *   using the preload pattern, with a <noscript> fallback.
 *
 * To regenerate: run `gulp critical` with the local dev site running.
 * If critical.min.css does not exist, falls back to standard stylesheet load.
 */
add_action( 'wp_head', function () {
  if ( is_front_page() ) {
    $slug = 'home';
  } elseif ( is_page() && has_category( 'landing-page' ) ) {
    $slug = 'landing-pages';
  } else {
    $slug = get_post_field( 'post_name', get_the_ID() );
  }
  $critical_file = get_stylesheet_directory() . "/assets/css/critical-{$slug}.min.css";

  // Fallback to global if page-specific doesn't exist
  if ( ! file_exists( $critical_file ) ) {
    $critical_file = get_stylesheet_directory() . '/assets/css/critical.min.css';
  }

  if ( file_exists( $critical_file ) ) {
    $critical_css = file_get_contents( $critical_file );
    echo '<style id="tlc-critical-css">' . $critical_css . '</style>' . "\n";
  }

  // 2. Load the Polyfill from the local assets folder
  $polyfill_path = get_stylesheet_directory() . '/assets/js/cssrelpreload.min.js';

  if ( file_exists( $polyfill_path ) ) {
    echo '<script id="loadcss-polyfill">' . file_get_contents( $polyfill_path ) . '</script>' . "\n";
  }
}, 2 );

/**
 * Convert stylesheets to async load when critical CSS is present.
 * Targets the main style and any page-specific styles (starting with tlc-).
 */


 add_filter( 'style_loader_tag', function ( $html, $handle ) {
  // Targets theme-custom-style AND any page-specific handles like tlc-contact-style
  $is_target = ( $handle === 'theme-custom-style' || strpos( $handle, 'tlc-' ) === 0 );

  if ( ! $is_target ) {
    return $html;
  }

  // Preload pattern: works with the inlined cssrelpreload.min.js polyfill
  $async = str_replace(
    "rel='stylesheet'",
    "rel='preload' as='style' onload=\"this.onload=null;this.rel='stylesheet'\"",
    $html
  );

  return $async . '<noscript>' . $html . '</noscript>' . "\n";
}, 10, 2 );