<?php

/**
 * Inline critical CSS and load the main stylesheet asynchronously.
 *
 * How it works:
 * - critical.min.css is generated by `gulp critical` and contains only
 *   above-the-fold styles extracted from style.min.css.
 * - That file is inlined directly into <head> so the browser can render
 *   immediately without waiting for a network request.
 * - style.min.css is then loaded asynchronously (non-render-blocking)
 *   using the preload pattern, with a <noscript> fallback.
 *
 * To regenerate: run `gulp critical` with the local dev site running.
 * If critical.min.css does not exist, falls back to standard stylesheet load.
 */
add_action( 'wp_head', function () {
  $critical_file = get_stylesheet_directory() . '/assets/css/critical.min.css';

  if ( ! file_exists( $critical_file ) ) {
    return;
  }

  $critical_css = file_get_contents( $critical_file );

  if ( empty( $critical_css ) ) {
    return;
  }

  echo '<style id="tlc-critical-css">' . $critical_css . '</style>' . "\n";
}, 1 );

/**
 * Convert the main stylesheet to async load when critical CSS is present.
 */
add_filter( 'style_loader_tag', function ( $html, $handle ) {
  if ( $handle !== 'theme-custom-style' ) {
    return $html;
  }

  $critical_file = get_stylesheet_directory() . '/assets/css/critical.min.css';

  if ( ! file_exists( $critical_file ) ) {
    return $html;
  }

  // Preload pattern: loads CSS without blocking render.
  // onload switches rel to stylesheet once loaded.
  // <noscript> ensures CSS loads for users with JS disabled.
  $async = str_replace(
    "rel='stylesheet'",
    "rel='preload' as='style' onload=\"this.onload=null;this.rel='stylesheet'\"",
    $html
  );

  return $async . '<noscript>' . $html . '</noscript>' . "\n";
}, 10, 2 );
